### ISSUE TITLE
Type error: Type '{ p: (props: any) => Element, ...}' has no properties in common with type 'Defaults'

### ISSUE THREAD

**Issue by timcouchoud** [mustaphaturhan/chakra-ui-markdown-renderer#21]
I have followign code:
`<Box marginTop="1rem">
            <ReactMarkdown
              components={ChakraUIRenderer(mdTheme("white"))}
              // eslint-disable-next-line react/no-children-prop
              children={workshop.description}
              escapeHtml={false}
            />
            ;
          </Box>`
And at build time I get following error:
`Type error: Type '{ p: (props: any) => Element; li: (props: any) => Element; h3: (props: any) => Element; }' has no properties in common with type 'Defaults'.`

I defined new theme in a separate file mdTheme.js:

```js
import { Text, Heading, ListItem } from "@chakra-ui/layout";

const mdTheme = (color) => {
  return {
    p: (props) => {
      const { children } = props;
      return (
        <Text mb={2} fontSize="md" color={color}>
          {children}
        </Text>
      );
    },
    li: (props) => {
      const { children } = props;
      return (
        <ListItem mb={2} fontSize="md" color={color}>
          {children}
        </ListItem>
      );
    },
    h3: (props) => {
      const { children } = props;
      return (
        <Heading as="h3" mb={2} fontSize="lg" color={color}>
          {children}
        </Heading>
      );
    },
  };
};

export default mdTheme;
```

Do you have an idea hwo to solve this error? Thx

**Comment by mustaphaturhan** [comment]
Hey @timcouchoud,

Thank you for letting me know. I think you are using react-markdown v7. Can you please updated `chakra-ui-markdown-renderer` to new version?
