### ISSUE TITLE
Could not find a declaration file for module 

### ISSUE THREAD

**Issue by supryantowp** [mustaphaturhan/chakra-ui-markdown-renderer#4]
could not find a declaration file for module 'chakra-ui-markdown-renderer'. '/Users/subadrun/projects/supryantowp/devcodes/node_modules/chakra-ui-markdown-renderer/dist/index.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/chakra-ui-markdown-renderer` if it exists or add a new declaration (.d.ts) file containing `declare module 'chakra-ui-markdown-renderer';`ts(7016)

I try to 
`npm I --save-dev @types/chakra-ui-markdown-renderer`

I got error

` npm ERR! 404  '@types/chakra-ui-markdown-renderer@latest' is not in the npm re│➜ npm run dev
gistry.`

**Comment by athuldevin** [comment]
i solved by importing like this const ChakraUIRenderer = require('chakra-ui-markdown-renderer');

**Comment by PymZoR** [comment]
Same problem

**Comment by Ptrskay3** [comment]
Create a file called `all.d.ts` next to your `package.json` with this content:
```ts
declare module "chakra-ui-markdown-renderer";
```
This project doesn't use TypeScript at the moment, so it is just for making the warnings disappear, and doesn't guarantee any type safety.

**Comment by supryantowp** [comment]
nive
