### ISSUE TITLE
TS Types

### ISSUE THREAD

**Issue by saranshgrover** [mustaphaturhan/chakra-ui-markdown-renderer#6]
Is this in the works? If not I can try to take a stab at it

**Comment by mustaphaturhan** [comment]
Hi @saranshgrover, this project isn't using typescript types at the moment but I am gonna create new release in few days. 
Any contribution will be appreciated if you want to help.

**Comment by s7tya** [comment]
so can't i use this with TypeScript?

I got an error with Next.js(TS)

```
Unhandled Runtime Error
TypeError: (0 , chakra_ui_markdown_renderer__WEBPACK_IMPORTED_MODULE_8__.ChakraUIRenderer) is not a function

```

**Comment by mustaphaturhan** [comment]
`chakra-ui-markdown-renderer` started to use types with version 3. closing issue :)
