### ISSUE TITLE
Spacing between ListItem at 24 a bit too large?

### ISSUE THREAD

**Issue by gronnbeck** [mustaphaturhan/chakra-ui-markdown-renderer#7]
First, thank you for sharing this repo. It made my day for my side project when I found it. 

So, isn't the spacing of List in see excerpt below or click (https://github.com/mustaphaturhan/chakra-ui-markdown-renderer/blob/master/src/index.js#L68) a bit too large? It is set to 24 which caused my application to get humongous large spacing between each element

```js
  list: props => {
    const { start, ordered, children, depth } = props;
    const attrs = getCoreProps(props);
    if (start !== null && start !== 1 && start !== undefined) {
      attrs.start = start.toString();
    }
    let styleType = 'disc';
    if (ordered) styleType = 'decimal';
    if (depth === 1) styleType = 'circle';
    return (
      <List
        spacing={24}
        as={ordered ? 'ol' : 'ul'}
        styleType={styleType}
        pl={4}
        {...attrs}
      >
        {children}
      </List>
    );
  },
```

I solved the issue on my hand by copying your default code and replacing 24 with 2 actually. So not a big issue for me. Altough I had to copy the `getCoreProps` as well to get it working.

Lastly, would be nice if it was easier to configure. But also see that it might be hard to do properly.

**Comment by mustaphaturhan** [comment]
Hey @gronnbeck, thank you for your feedback and you're right. I wasn't aware of that spacing prop and I am gonna change `24` to `2` in few days.

**Comment by jakewheeler** [comment]
I have also run into this issue. Happy to help out if needed.
